---
version: '3.4'

services:
  keycloak:
    image: docker.chameleoncloud.org/keycloak:dev
    environment:
      DB_VENDOR: mariadb
      DB_USER: keycloak
      DB_PASSWORD: keycloak_pass
      KEYCLOAK_LOGLEVEL: DEBUG
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HOSTNAME: ${VIRTUAL_HOST}
      KEYCLOAK_ALWAYS_HTTPS: "true"
      PROXY_ADDRESS_FORWARDING: "true"
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
    expose:
      - 8080

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak_pass
    volumes:
      - mariadb_data:/var/lib/mysql

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: ${EMAIL}
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost_d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      DHPARAM_GENERATION: "false"
    volumes:
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost_d:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443

volumes:
  mariadb_data:
  nginx_certs:
  nginx_vhost_d:
  nginx_html:
